// Taxonomy + seed data. Edit these lists to change the filters shown on the site.
window.TAXONOMY = {
  categories: [
    { id: 'frontend', label: 'Frontend / UI' },
    { id: 'backend', label: 'Backend / API' },
    { id: 'deploy', label: 'Deployment & Hosting' },
    { id: 'database', label: 'Database' },
    { id: 'auth', label: 'Auth & Security' },
    { id: 'performance', label: 'Performance' },
    { id: 'mobile', label: 'Mobile' },
    { id: 'ai', label: 'AI / ML' },
    { id: 'devops', label: 'CI / DevOps' },
    { id: 'design', label: 'Design & UX' },
    { id: 'other', label: 'Other' },
  ],
  statuses: [
    { id: 'open', label: 'Open' },
    { id: 'progress', label: 'In progress' },
    { id: 'solved', label: 'Solved' },
  ],
  urgencies: [
    { id: 'low', label: 'Low' },
    { id: 'normal', label: 'Normal' },
    { id: 'high', label: 'Urgent' },
  ],
};

const day = 864e5, now = Date.now();
window.SEED_ISSUES = [
  { id: 's1', title: 'Next.js build fails on Vercel but works locally', category: 'deploy', urgency: 'high', status: 'open',
    repo: 'https://github.com/example/portfolio-next', site: 'https://portfolio-example.vercel.app', tags: ['nextjs', 'vercel', 'typescript'],
    author: 'maya_dev', createdAt: now - 2 * 36e5, votes: 7,
    body: 'Running `npm run build` locally works fine, but on Vercel I get:\n\nType error: Cannot find module \'@/components/Hero\'\n\nI already checked tsconfig paths. Any ideas?',
    replies: [] },
  { id: 's2', title: 'CSS grid layout breaks on Safari iOS', category: 'frontend', urgency: 'normal', status: 'progress',
    repo: 'https://github.com/example/bakery-site', tags: ['css', 'safari', 'responsive'], author: 'jonas', createdAt: now - day, votes: 4,
    body: 'My product grid collapses into a single squashed column on iPhone Safari. Chrome/Firefox fine. Using `grid-template-columns: repeat(auto-fill, minmax(200px, 1fr))` with `gap`.',
    replies: [{ id: 'r1', author: 'cssnerd', body: 'Check if a parent has `display:flex` with no min-width — Safari handles min-width:auto differently. Try `min-width:0` on the grid container.', createdAt: now - 20 * 36e5, votes: 3 }] },
  { id: 's3', title: 'Supabase row level security blocks my inserts', category: 'database', urgency: 'normal', status: 'solved',
    repo: 'https://github.com/example/todo-supa', tags: ['supabase', 'postgres', 'rls'], author: 'lee', createdAt: now - 3 * day, votes: 12,
    body: 'After enabling RLS every insert returns "new row violates row-level security policy". I have a policy for SELECT.',
    replies: [{ id: 'r2', author: 'dbwizard', body: 'You need a separate INSERT policy with a WITH CHECK clause, e.g. `with check (auth.uid() = user_id)`. SELECT policies do not cover inserts.', createdAt: now - 3 * day + 36e5, votes: 9, accepted: true }] },
  { id: 's4', title: 'Express API returns CORS error only in production', category: 'backend', urgency: 'high', status: 'open',
    repo: 'https://github.com/example/shop-api', tags: ['node', 'express', 'cors'], author: 'priya', createdAt: now - 5 * 36e5, votes: 5,
    body: 'Frontend on Netlify, API on Render. Locally everything works. In prod: "No Access-Control-Allow-Origin header". I use the cors package with origin set to my Netlify URL.',
    replies: [] },
  { id: 's5', title: 'Lighthouse performance score stuck at 45', category: 'performance', urgency: 'low', status: 'open',
    site: 'https://example-blog.dev', tags: ['lighthouse', 'images', 'seo'], author: 'Anonymous', createdAt: now - 6 * day, votes: 2,
    body: 'Largest Contentful Paint is 6s. It\'s a mostly static blog. Where do I start?', replies: [] },
  { id: 's6', title: 'GitHub Actions deploy step can\'t find secrets', category: 'devops', urgency: 'normal', status: 'open',
    repo: 'https://github.com/example/docs-site', tags: ['github-actions', 'ci'], author: 'sam', createdAt: now - 2 * day, votes: 3,
    body: 'The workflow runs on pull_request from forks and `${{ secrets.DEPLOY_TOKEN }}` is empty.', replies: [] },
  { id: 's7', title: 'Chatbot with OpenAI-compatible API keeps losing context', category: 'ai', urgency: 'normal', status: 'progress',
    repo: 'https://github.com/example/support-bot', tags: ['llm', 'python', 'chatbot'], author: 'kai', createdAt: now - 4 * day, votes: 6,
    body: 'Each message seems answered in isolation — the bot forgets what the user said earlier.',
    replies: [{ id: 'r3', author: 'mlhelper', body: 'Most chat APIs are stateless — you have to send the whole message history each request. Are you appending previous turns?', createdAt: now - 4 * day + 2 * 36e5, votes: 4 }] },
  { id: 's8', title: 'OAuth redirect loop after Google login', category: 'auth', urgency: 'high', status: 'open',
    repo: 'https://github.com/example/saas-starter', tags: ['oauth', 'nextauth', 'cookies'], author: 'rin', createdAt: now - 9 * 36e5, votes: 8,
    body: 'After signing in with Google the app redirects to /login again forever. Only on the custom domain, not on the preview URL.', replies: [] },
];
